# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(560, 616)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/icon.fw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.isGameLocated = QtWidgets.QLabel(Form)
        self.isGameLocated.setGeometry(QtCore.QRect(10, 181, 261, 16))
        self.isGameLocated.setObjectName("isGameLocated")
        self.display = QtWidgets.QLabel(Form)
        self.display.setGeometry(QtCore.QRect(10, 200, 251, 251))
        self.display.setText("")
        self.display.setPixmap(QtGui.QPixmap("resources/gridTemplate.png"))
        self.display.setScaledContents(True)
        self.display.setWordWrap(False)
        self.display.setObjectName("display")
        self.commandsBox = QtWidgets.QGroupBox(Form)
        self.commandsBox.setGeometry(QtCore.QRect(270, 190, 281, 261))
        self.commandsBox.setObjectName("commandsBox")
        self.inputWord = QtWidgets.QPushButton(self.commandsBox)
        self.inputWord.setGeometry(QtCore.QRect(10, 30, 261, 31))
        self.inputWord.setObjectName("inputWord")
        self.screenshotGrid = QtWidgets.QPushButton(self.commandsBox)
        self.screenshotGrid.setGeometry(QtCore.QRect(10, 70, 261, 23))
        self.screenshotGrid.setObjectName("screenshotGrid")
        self.gridBox = QtWidgets.QPlainTextEdit(self.commandsBox)
        self.gridBox.setGeometry(QtCore.QRect(70, 140, 121, 111))
        font = QtGui.QFont()
        font.setFamily("Cooper Std Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gridBox.setFont(font)
        self.gridBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridBox.setFrameShape(QtWidgets.QFrame.Box)
        self.gridBox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gridBox.setLineWidth(1)
        self.gridBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gridBox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gridBox.setReadOnly(True)
        self.gridBox.setCenterOnScroll(False)
        self.gridBox.setObjectName("gridBox")
        self.readGrid = QtWidgets.QPushButton(self.commandsBox)
        self.readGrid.setGeometry(QtCore.QRect(10, 100, 261, 23))
        self.readGrid.setObjectName("readGrid")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 541, 168))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.logoLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.logoLayout.setContentsMargins(0, 0, 0, 0)
        self.logoLayout.setObjectName("logoLayout")
        self.logo = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setAutoFillBackground(False)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("resources/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.logoLayout.addWidget(self.logo)
        self.optionsBox = QtWidgets.QGroupBox(Form)
        self.optionsBox.setGeometry(QtCore.QRect(10, 460, 541, 141))
        self.optionsBox.setObjectName("optionsBox")
        self.ocrMethodBox = QtWidgets.QGroupBox(self.optionsBox)
        self.ocrMethodBox.setGeometry(QtCore.QRect(10, 20, 120, 61))
        self.ocrMethodBox.setObjectName("ocrMethodBox")
        self.radioPyautogui = QtWidgets.QRadioButton(self.ocrMethodBox)
        self.radioPyautogui.setGeometry(QtCore.QRect(10, 40, 101, 17))
        self.radioPyautogui.setObjectName("radioPyautogui")
        self.radioTesseract = QtWidgets.QRadioButton(self.ocrMethodBox)
        self.radioTesseract.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.radioTesseract.setChecked(True)
        self.radioTesseract.setObjectName("radioTesseract")
        self.tabWidget = QtWidgets.QTabWidget(self.optionsBox)
        self.tabWidget.setGeometry(QtCore.QRect(140, 10, 391, 121))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tesseractTab = QtWidgets.QWidget()
        self.tesseractTab.setObjectName("tesseractTab")
        self.tesseractThresholdSlider = QtWidgets.QSlider(self.tesseractTab)
        self.tesseractThresholdSlider.setGeometry(QtCore.QRect(10, 30, 151, 22))
        self.tesseractThresholdSlider.setMaximum(255)
        self.tesseractThresholdSlider.setProperty("value", 30)
        self.tesseractThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tesseractThresholdSlider.setObjectName("tesseractThresholdSlider")
        self.tesseractThresholdLabel = QtWidgets.QLabel(self.tesseractTab)
        self.tesseractThresholdLabel.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.tesseractThresholdLabel.setObjectName("tesseractThresholdLabel")
        self.tesseractThresholdNumber = QtWidgets.QLabel(self.tesseractTab)
        self.tesseractThresholdNumber.setGeometry(QtCore.QRect(150, 10, 47, 16))
        self.tesseractThresholdNumber.setObjectName("tesseractThresholdNumber")
        self.tabWidget.addTab(self.tesseractTab, "")
        self.pyautoguiTab = QtWidgets.QWidget()
        self.pyautoguiTab.setObjectName("pyautoguiTab")
        self.tabWidget.addTab(self.pyautoguiTab, "")
        self.isGameLocated.raise_()
        self.commandsBox.raise_()
        self.horizontalLayoutWidget.raise_()
        self.display.raise_()
        self.optionsBox.raise_()

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tesseractThresholdSlider.valueChanged['int'].connect(self.tesseractThresholdNumber.setNum)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PyLex"))
        self.isGameLocated.setText(_translate("Form", "Bookworm Adventures is not located!"))
        self.commandsBox.setTitle(_translate("Form", "Commands"))
        self.inputWord.setText(_translate("Form", "Input Word"))
        self.screenshotGrid.setText(_translate("Form", "Screenshot grid"))
        self.gridBox.setPlainText(_translate("Form", "\n"
"\n"
""))
        self.gridBox.setPlaceholderText(_translate("Form", "ABCD"))
        self.readGrid.setText(_translate("Form", "Read grid"))
        self.optionsBox.setTitle(_translate("Form", "Options"))
        self.ocrMethodBox.setTitle(_translate("Form", "OCR Method"))
        self.radioPyautogui.setText(_translate("Form", "PyAutoGUI"))
        self.radioTesseract.setText(_translate("Form", "Google Tesseract"))
        self.tesseractThresholdLabel.setText(_translate("Form", "Google Tesseract threshold:"))
        self.tesseractThresholdNumber.setText(_translate("Form", "30"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tesseractTab), _translate("Form", "Google Tesseract"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pyautoguiTab), _translate("Form", "PyAutoGUI"))


