# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(684, 772)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/icon.fw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.logoLayout = QtWidgets.QHBoxLayout()
        self.logoLayout.setObjectName("logoLayout")
        self.logo = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setAutoFillBackground(False)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("resources/logof.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.logoLayout.addWidget(self.logo)
        self.verticalLayout_6.addLayout(self.logoLayout)
        self.middleBox = QtWidgets.QWidget(Form)
        self.middleBox.setObjectName("middleBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.middleBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.displayBox = QtWidgets.QWidget(self.middleBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayBox.sizePolicy().hasHeightForWidth())
        self.displayBox.setSizePolicy(sizePolicy)
        self.displayBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.displayBox.setObjectName("displayBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.displayBox)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.isGameLocated = QtWidgets.QLabel(self.displayBox)
        self.isGameLocated.setMaximumSize(QtCore.QSize(16777215, 15))
        self.isGameLocated.setBaseSize(QtCore.QSize(0, 0))
        self.isGameLocated.setStyleSheet("color:darkred;\n"
"background-color:rgb(255, 184, 184);")
        self.isGameLocated.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.isGameLocated.setObjectName("isGameLocated")
        self.verticalLayout_3.addWidget(self.isGameLocated)
        self.searchForGameWindow = QtWidgets.QPushButton(self.displayBox)
        self.searchForGameWindow.setObjectName("searchForGameWindow")
        self.verticalLayout_3.addWidget(self.searchForGameWindow)
        self.dictionary = QtWidgets.QPushButton(self.displayBox)
        self.dictionary.setObjectName("dictionary")
        self.verticalLayout_3.addWidget(self.dictionary)
        self.displayContainer = QtWidgets.QWidget(self.displayBox)
        self.displayContainer.setObjectName("displayContainer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.displayContainer)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.display = QtWidgets.QLabel(self.displayContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display.sizePolicy().hasHeightForWidth())
        self.display.setSizePolicy(sizePolicy)
        self.display.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.display.setText("")
        self.display.setPixmap(QtGui.QPixmap("resources/gridTemplate.png"))
        self.display.setScaledContents(True)
        self.display.setWordWrap(False)
        self.display.setObjectName("display")
        self.gridLayout_3.addWidget(self.display, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.displayContainer)
        self.horizontalLayout.addWidget(self.displayBox)
        self.commandsBox = QtWidgets.QGroupBox(self.middleBox)
        self.commandsBox.setObjectName("commandsBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.commandsBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.inputWord = QtWidgets.QPushButton(self.commandsBox)
        self.inputWord.setMinimumSize(QtCore.QSize(0, 31))
        self.inputWord.setMaximumSize(QtCore.QSize(1000, 31))
        self.inputWord.setObjectName("inputWord")
        self.verticalLayout_4.addWidget(self.inputWord)
        self.getPossibleWords = QtWidgets.QPushButton(self.commandsBox)
        self.getPossibleWords.setMinimumSize(QtCore.QSize(0, 23))
        self.getPossibleWords.setMaximumSize(QtCore.QSize(16777215, 23))
        self.getPossibleWords.setObjectName("getPossibleWords")
        self.verticalLayout_4.addWidget(self.getPossibleWords)
        self.readGrid = QtWidgets.QPushButton(self.commandsBox)
        self.readGrid.setMinimumSize(QtCore.QSize(0, 23))
        self.readGrid.setMaximumSize(QtCore.QSize(16777215, 23))
        self.readGrid.setObjectName("readGrid")
        self.verticalLayout_4.addWidget(self.readGrid)
        self.screenshotGrid = QtWidgets.QPushButton(self.commandsBox)
        self.screenshotGrid.setMinimumSize(QtCore.QSize(0, 23))
        self.screenshotGrid.setMaximumSize(QtCore.QSize(16777215, 23))
        self.screenshotGrid.setObjectName("screenshotGrid")
        self.verticalLayout_4.addWidget(self.screenshotGrid)
        self.gridAndWordsBox = QtWidgets.QWidget(self.commandsBox)
        self.gridAndWordsBox.setObjectName("gridAndWordsBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridAndWordsBox)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(9, -1, -1, -1)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.gridBox = QtWidgets.QPlainTextEdit(self.gridAndWordsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridBox.sizePolicy().hasHeightForWidth())
        self.gridBox.setSizePolicy(sizePolicy)
        self.gridBox.setMinimumSize(QtCore.QSize(100, 0))
        self.gridBox.setMaximumSize(QtCore.QSize(124, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cooper Std Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gridBox.setFont(font)
        self.gridBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridBox.setFrameShape(QtWidgets.QFrame.Box)
        self.gridBox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gridBox.setLineWidth(1)
        self.gridBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gridBox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gridBox.setReadOnly(True)
        self.gridBox.setPlainText("")
        self.gridBox.setCenterOnScroll(False)
        self.gridBox.setObjectName("gridBox")
        self.gridLayout.addWidget(self.gridBox, 0, 0, 1, 1)
        self.possibleWordsBox = QtWidgets.QPlainTextEdit(self.gridAndWordsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.possibleWordsBox.sizePolicy().hasHeightForWidth())
        self.possibleWordsBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cooper Std Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.possibleWordsBox.setFont(font)
        self.possibleWordsBox.setReadOnly(True)
        self.possibleWordsBox.setPlainText("")
        self.possibleWordsBox.setObjectName("possibleWordsBox")
        self.gridLayout.addWidget(self.possibleWordsBox, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.gridAndWordsBox)
        self.horizontalLayout.addWidget(self.commandsBox)
        self.verticalLayout_6.addWidget(self.middleBox)
        self.optionsBox = QtWidgets.QGroupBox(Form)
        self.optionsBox.setObjectName("optionsBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.optionsBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wordsToTryBox = QtWidgets.QWidget(self.optionsBox)
        self.wordsToTryBox.setObjectName("wordsToTryBox")
        self.formLayout = QtWidgets.QFormLayout(self.wordsToTryBox)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.wordsToTryLabel = QtWidgets.QLabel(self.wordsToTryBox)
        self.wordsToTryLabel.setObjectName("wordsToTryLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.wordsToTryLabel)
        self.wordsToTrySpinBox = QtWidgets.QSpinBox(self.wordsToTryBox)
        self.wordsToTrySpinBox.setToolTip("")
        self.wordsToTrySpinBox.setProperty("value", 5)
        self.wordsToTrySpinBox.setObjectName("wordsToTrySpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.wordsToTrySpinBox)
        self.typingSpeedLabel = QtWidgets.QLabel(self.wordsToTryBox)
        self.typingSpeedLabel.setObjectName("typingSpeedLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.typingSpeedLabel)
        self.typingSpeedSpinBox = QtWidgets.QSpinBox(self.wordsToTryBox)
        self.typingSpeedSpinBox.setMinimum(1)
        self.typingSpeedSpinBox.setMaximum(10)
        self.typingSpeedSpinBox.setProperty("value", 5)
        self.typingSpeedSpinBox.setObjectName("typingSpeedSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.typingSpeedSpinBox)
        self.submitImmediateLabel = QtWidgets.QLabel(self.wordsToTryBox)
        self.submitImmediateLabel.setObjectName("submitImmediateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.submitImmediateLabel)
        self.submitImmediateBox = QtWidgets.QCheckBox(self.wordsToTryBox)
        self.submitImmediateBox.setChecked(False)
        self.submitImmediateBox.setTristate(False)
        self.submitImmediateBox.setObjectName("submitImmediateBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.submitImmediateBox)
        self.gridLayout_2.addWidget(self.wordsToTryBox, 0, 1, 1, 1)
        self.ocrMethodBox = QtWidgets.QGroupBox(self.optionsBox)
        self.ocrMethodBox.setObjectName("ocrMethodBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ocrMethodBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioPyautogui = QtWidgets.QRadioButton(self.ocrMethodBox)
        self.radioPyautogui.setChecked(True)
        self.radioPyautogui.setObjectName("radioPyautogui")
        self.verticalLayout.addWidget(self.radioPyautogui)
        self.radioTesseract = QtWidgets.QRadioButton(self.ocrMethodBox)
        self.radioTesseract.setChecked(False)
        self.radioTesseract.setObjectName("radioTesseract")
        self.verticalLayout.addWidget(self.radioTesseract)
        self.gridLayout_2.addWidget(self.ocrMethodBox, 0, 0, 1, 1)
        self.sortWordsByBox = QtWidgets.QGroupBox(self.optionsBox)
        self.sortWordsByBox.setObjectName("sortWordsByBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sortWordsByBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioSortByScore = QtWidgets.QRadioButton(self.sortWordsByBox)
        self.radioSortByScore.setChecked(True)
        self.radioSortByScore.setObjectName("radioSortByScore")
        self.verticalLayout_2.addWidget(self.radioSortByScore)
        self.radioSortByLength = QtWidgets.QRadioButton(self.sortWordsByBox)
        self.radioSortByLength.setObjectName("radioSortByLength")
        self.verticalLayout_2.addWidget(self.radioSortByLength)
        self.gridLayout_2.addWidget(self.sortWordsByBox, 1, 0, 1, 1)
        self.thresholdValueBox = QtWidgets.QWidget(self.optionsBox)
        self.thresholdValueBox.setObjectName("thresholdValueBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.thresholdValueBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tesseractThresholdLabel = QtWidgets.QLabel(self.thresholdValueBox)
        self.tesseractThresholdLabel.setObjectName("tesseractThresholdLabel")
        self.verticalLayout_5.addWidget(self.tesseractThresholdLabel)
        self.tesseractThresholdNumber = QtWidgets.QLabel(self.thresholdValueBox)
        self.tesseractThresholdNumber.setObjectName("tesseractThresholdNumber")
        self.verticalLayout_5.addWidget(self.tesseractThresholdNumber)
        self.tesseractThresholdSlider = QtWidgets.QSlider(self.thresholdValueBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tesseractThresholdSlider.sizePolicy().hasHeightForWidth())
        self.tesseractThresholdSlider.setSizePolicy(sizePolicy)
        self.tesseractThresholdSlider.setMaximum(255)
        self.tesseractThresholdSlider.setProperty("value", 50)
        self.tesseractThresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tesseractThresholdSlider.setObjectName("tesseractThresholdSlider")
        self.verticalLayout_5.addWidget(self.tesseractThresholdSlider)
        self.gridLayout_2.addWidget(self.thresholdValueBox, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.optionsBox)

        self.retranslateUi(Form)
        self.tesseractThresholdSlider.valueChanged['int'].connect(self.tesseractThresholdNumber.setNum)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tesseractThresholdSlider, self.inputWord)
        Form.setTabOrder(self.inputWord, self.getPossibleWords)
        Form.setTabOrder(self.getPossibleWords, self.readGrid)
        Form.setTabOrder(self.readGrid, self.screenshotGrid)
        Form.setTabOrder(self.screenshotGrid, self.gridBox)
        Form.setTabOrder(self.gridBox, self.possibleWordsBox)
        Form.setTabOrder(self.possibleWordsBox, self.radioPyautogui)
        Form.setTabOrder(self.radioPyautogui, self.radioTesseract)
        Form.setTabOrder(self.radioTesseract, self.wordsToTrySpinBox)
        Form.setTabOrder(self.wordsToTrySpinBox, self.radioSortByScore)
        Form.setTabOrder(self.radioSortByScore, self.radioSortByLength)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PyLex"))
        self.isGameLocated.setText(_translate("Form", "Bookworm Adventures is not located!"))
        self.searchForGameWindow.setToolTip(_translate("Form", "<html><head/><body><p>Upon clicking this button, PyLex will search for an instance of Bookworm Adventures volumes 1 or 2. Only usable when the game process has not already been located by PyLex.</p></body></html>"))
        self.searchForGameWindow.setText(_translate("Form", "Search for the game window"))
        self.dictionary.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Dictionary</span></p><p>A list of words PyLex uses to look up possible words to submit. By clicking on this button, you can load custom dictionaries, however the default dictionaries bundled with PyLex are ripped from the game\'s files, and is therefore already optimal.</p></body></html>"))
        self.dictionary.setText(_translate("Form", "Dictionary: None"))
        self.display.setToolTip(_translate("Form", "<html><head/><body><p>A display for the screenshots.</p></body></html>"))
        self.commandsBox.setTitle(_translate("Form", "Commands"))
        self.inputWord.setToolTip(_translate("Form", "<html><head/><body><p>Screenshots and reads the grid, then proceeds to type out words to submit.</p></body></html>"))
        self.inputWord.setText(_translate("Form", "Input Word"))
        self.getPossibleWords.setToolTip(_translate("Form", "<html><head/><body><p>Screenshots and reads the grid, then outputs the best possible words below without automatically inputting them.</p></body></html>"))
        self.getPossibleWords.setText(_translate("Form", "Get possible words"))
        self.readGrid.setToolTip(_translate("Form", "<html><head/><body><p>Screenshots and reads the grid, then outputs it to the display box below.</p></body></html>"))
        self.readGrid.setText(_translate("Form", "Read grid"))
        self.screenshotGrid.setToolTip(_translate("Form", "<html><head/><body><p>Screenshots the grid and puts the image on the left.</p></body></html>"))
        self.screenshotGrid.setText(_translate("Form", "Screenshot grid"))
        self.gridBox.setToolTip(_translate("Form", "<html><head/><body><p>A display for the read grid.</p></body></html>"))
        self.gridBox.setPlaceholderText(_translate("Form", "ABCD"))
        self.possibleWordsBox.setToolTip(_translate("Form", "<html><head/><body><p>A display for the list of possible words.</p></body></html>"))
        self.possibleWordsBox.setPlaceholderText(_translate("Form", "misunderstanding"))
        self.optionsBox.setTitle(_translate("Form", "Options"))
        self.wordsToTryLabel.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Words to try</span></p><p>The number of words to try typing out into the grid before giving up. For example, if this was 5, PyLex will try typing out the best 5 words it can find. If none of them work, it will then give up.</p></body></html>"))
        self.wordsToTryLabel.setText(_translate("Form", "Words to try:"))
        self.typingSpeedLabel.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Typing speed</span></p><p>How fast PyLex will type words, with 1 being the slowest and 10 being the fastest.</p></body></html>"))
        self.typingSpeedLabel.setText(_translate("Form", "Typing speed:"))
        self.submitImmediateLabel.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Submit immediately</span></p><p>When unticked, PyLex will give you some time to look at the word it has typed before it submits.</p></body></html>"))
        self.submitImmediateLabel.setText(_translate("Form", "Submit immediately:"))
        self.submitImmediateBox.setText(_translate("Form", "PyLex will not submit immediately."))
        self.ocrMethodBox.setTitle(_translate("Form", "OCR Method"))
        self.radioPyautogui.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">PyAutoGUI</span></p><p>A reading approach using PyAutoGUI using sample images. More reliable than Google Tesseract.</p></body></html>"))
        self.radioPyautogui.setText(_translate("Form", "PyAutoGUI"))
        self.radioTesseract.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Google Tesseract</span></p><p>A type of OCR technology provided by Google. It\'s less reliable than PyAutoGUI, and a little experimental.</p></body></html>"))
        self.radioTesseract.setText(_translate("Form", "Google Tesseract"))
        self.sortWordsByBox.setTitle(_translate("Form", "Sort words by"))
        self.radioSortByScore.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Sort words by score</span></p><p>Sorts words by their score in Bookworm Adventures.</p></body></html>"))
        self.radioSortByScore.setText(_translate("Form", "Score"))
        self.radioSortByLength.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Sort words by length</span></p><p>Sorts words by how long they are. If words are the same length, they are sorted alphabetically.</p></body></html>"))
        self.radioSortByLength.setText(_translate("Form", "Length"))
        self.tesseractThresholdLabel.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Thresholding value</span></p><p>How strongly PyLex should filter out black in screenshots, with 0 (far left) filtering out the most and 255 (far right) filtering out the least.</p></body></html>"))
        self.tesseractThresholdLabel.setText(_translate("Form", "Thresholding value:"))
        self.tesseractThresholdNumber.setText(_translate("Form", "50"))


